/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    projects: Project;
    services: Service;
    publications: Publication;
    'publication-categories': PublicationCategory;
    'team-members': TeamMember;
    partners: Partner;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    partners: {
      projects: 'projects';
    };
  };
  collectionsSelect: {
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    publications: PublicationsSelect<false> | PublicationsSelect<true>;
    'publication-categories': PublicationCategoriesSelect<false> | PublicationCategoriesSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    home: Home;
    'theory-of-change': TheoryOfChange;
    'publications-page': PublicationsPage;
    'portfolio-page': PortfolioPage;
    'contact-page': ContactPage;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    'theory-of-change': TheoryOfChangeSelect<false> | TheoryOfChangeSelect<true>;
    'publications-page': PublicationsPageSelect<false> | PublicationsPageSelect<true>;
    'portfolio-page': PortfolioPageSelect<false> | PortfolioPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Cada projeto vira um card em /portfolio e uma página própria em /portfolio/[slug].
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  client: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Opcional. Quando preenchido, o logo cadastrado em Parceiros aparece pequeno no card e no topo da página do projeto. Sem ele, o card mostra só o nome — que continua vindo do campo Cliente acima.
   */
  partner?: (string | null) | Partner;
  /**
   * Uma a duas linhas para o card da listagem e para a abertura da página do projeto. Se ficar vazio, o card usa o começo do Desafio e a abertura da página não exibe nada — nunca repete o texto do Desafio logo abaixo.
   */
  summary?: string | null;
  challenge: string;
  results: string;
  /**
   * Opcional. Texto longo exibido só na página do projeto, abaixo de Desafio e Resultados.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Imagem do card e do topo da página do projeto.
   */
  image: {
    /**
     * Tem prioridade sobre a URL externa.
     */
    media?: (string | null) | Media;
    /**
     * Usada apenas enquanto não houver upload — ex.: placeholders do Unsplash.
     */
    externalUrl?: string | null;
    /**
     * Descreve a imagem para leitores de tela. Deixe vazio se for decorativa.
     */
    alt: string;
  };
  /**
   * Define a cor do card.
   */
  ecosystem: 'Meio Ambiente' | 'Educação' | 'Direitos Humanos' | 'Cultura' | 'Finanças' | 'Saúde' | 'Empreendedorismo';
  /**
   * Aceita texto livre, ex.: "2024 — em andamento".
   */
  year: string;
  /**
   * Alimenta o filtro por serviço. Reaproveite exatamente o mesmo texto entre projetos do mesmo tipo, senão viram duas opções distintas no filtro.
   */
  service: string;
  /**
   * Natureza da organização atendida.
   */
  segment?:
    | (
        | 'Agência de Cooperação Internacional'
        | 'Empresa'
        | 'Fundação ou Instituto Empresarial'
        | 'Fundação ou Instituto Familiar'
        | 'Governo'
        | 'Negócio de Impacto'
        | 'Organização de Sociedade Civil'
        | 'Organismo Internacional'
        | 'Outros'
      )
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  /**
   * Menor número aparece primeiro.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Logos do carrossel "Com quem trabalhamos", na home — e o logo que pode aparecer nos cards do portfólio.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: string;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Aparece no carrossel da home e, pequeno, no card de cada projeto ligado a este cliente. Prefira SVG ou PNG com fundo transparente.
   */
  logo: {
    /**
     * Tem prioridade sobre a URL externa.
     */
    media?: (string | null) | Media;
    /**
     * Usada apenas enquanto não houver upload — ex.: placeholders do Unsplash.
     */
    externalUrl?: string | null;
    /**
     * Descreve a imagem para leitores de tela. Deixe vazio se for decorativa.
     */
    alt: string;
  };
  /**
   * A ligação é feita no projeto, em Portfólio → Cliente (logo). Um cliente pode ter vários projetos: o logo do carrossel leva ao projeto quando há só um, e à listagem filtrada quando há mais.
   */
  projects?: {
    docs?: (string | Project)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Menor número aparece primeiro.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Descreve a imagem para leitores de tela e para quando ela não carrega.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Cards do bloco "O que entregamos", na home e na Teoria da Mudança.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  title: string;
  body: string;
  /**
   * SVG da marca exibido no card.
   */
  icon:
    | '/brand/icons/Group 2.svg'
    | '/brand/icons/Group 3.svg'
    | '/brand/icons/Group 4.svg'
    | '/brand/icons/Group 5.svg'
    | '/brand/icons/Group 6.svg'
    | '/brand/icons/Group 7.svg'
    | '/brand/icons/Group 8.svg'
    | '/brand/icons/Group 9.svg'
    | '/brand/icons/Group 10.svg'
    | '/brand/icons/Group 11.svg'
    | '/brand/icons/Group 12.svg'
    | '/brand/icons/Group 13.svg'
    | '/brand/icons/Group 14.svg'
    | '/brand/icons/Group 15.svg'
    | '/brand/icons/Group 16.svg';
  /**
   * Menor número aparece primeiro. A numeração 01, 02… do card é gerada a partir daqui.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Acervo de /publicacoes. Ordenado pela data de publicação, mais recente primeiro.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications".
 */
export interface Publication {
  id: string;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Uma a duas linhas. Aparece no card da listagem.
   */
  synopsis: string;
  cover: {
    /**
     * Tem prioridade sobre a URL externa.
     */
    media?: (string | null) | Media;
    /**
     * Usada apenas enquanto não houver upload — ex.: placeholders do Unsplash.
     */
    externalUrl?: string | null;
    /**
     * Descreve a imagem para leitores de tela. Deixe vazio se for decorativa.
     */
    alt: string;
  };
  /**
   * O corpo da página. Num artigo é o texto completo; num download ou link externo, o texto que apresenta e contextualiza a publicação.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * PDF, documento, planilha, apresentação ou pacote. A página oferece o download.
   */
  file?: (string | null) | Media;
  /**
   * Para onde o botão da página leva.
   */
  externalUrl?: string | null;
  /**
   * Rótulo do botão de download ou de acesso. Vazio usa o padrão do tipo — ex.: "Baixar publicação".
   */
  actionLabel?: string | null;
  publishedAt: string;
  author?: string | null;
  /**
   * Alimentam o filtro da listagem.
   */
  categories?: (string | PublicationCategory)[] | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  /**
   * Decide quais campos aparecem acima e o que o card oferece.
   */
  type: 'article' | 'download' | 'external';
  /**
   * A home mostra as 3 publicações destacadas mais recentes; sem destaques, mostra as 3 últimas.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Rótulos usados para filtrar /publicacoes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publication-categories".
 */
export interface PublicationCategory {
  id: string;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Cor do sistema. A cor do texto vem junto, pela tabela de contraste do guia.
   */
  color: 'purple' | 'green' | 'coral' | 'yellow' | 'periwinkle' | 'sand' | 'mint';
  /**
   * Menor número aparece primeiro.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Uma pessoa por registro. O campo Grupo define em qual bloco da home ela aparece.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: string;
  name: string;
  specialty: string;
  /**
   * Formação e trajetória em um parágrafo. Aparece sobre o retrato quando o mouse passa pelo card (e sempre visível no celular, que não tem hover).
   */
  bio?: string | null;
  photo: {
    /**
     * Tem prioridade sobre a URL externa.
     */
    media?: (string | null) | Media;
    /**
     * Usada apenas enquanto não houver upload — ex.: placeholders do Unsplash.
     */
    externalUrl?: string | null;
    /**
     * Descreve a imagem para leitores de tela. Deixe vazio se for decorativa.
     */
    alt: string;
  };
  group: 'team' | 'board';
  /**
   * Menor número aparece primeiro.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null)
    | ({
        relationTo: 'publications';
        value: string | Publication;
      } | null)
    | ({
        relationTo: 'publication-categories';
        value: string | PublicationCategory;
      } | null)
    | ({
        relationTo: 'team-members';
        value: string | TeamMember;
      } | null)
    | ({
        relationTo: 'partners';
        value: string | Partner;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  client?: T;
  generateSlug?: T;
  slug?: T;
  partner?: T;
  summary?: T;
  challenge?: T;
  results?: T;
  description?: T;
  image?:
    | T
    | {
        media?: T;
        externalUrl?: T;
        alt?: T;
      };
  ecosystem?: T;
  year?: T;
  service?: T;
  segment?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  icon?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications_select".
 */
export interface PublicationsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  synopsis?: T;
  cover?:
    | T
    | {
        media?: T;
        externalUrl?: T;
        alt?: T;
      };
  content?: T;
  file?: T;
  externalUrl?: T;
  actionLabel?: T;
  publishedAt?: T;
  author?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  type?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publication-categories_select".
 */
export interface PublicationCategoriesSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  color?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  specialty?: T;
  bio?: T;
  photo?:
    | T
    | {
        media?: T;
        externalUrl?: T;
        alt?: T;
      };
  group?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  logo?:
    | T
    | {
        media?: T;
        externalUrl?: T;
        alt?: T;
      };
  projects?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Hero, selos e os cards empilhados de destaque.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: string;
  hero: {
    eyebrow: string;
    title: string;
    body: string;
  };
  /**
   * Exibidos abaixo do hero.
   */
  affiliations?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Os cards empilhados da home. A numeração 01, 02… é gerada a partir da ordem desta lista.
   */
  showcase?:
    | {
        client: string;
        category: string;
        title: string;
        description: string;
        image: {
          /**
           * Tem prioridade sobre a URL externa.
           */
          media?: (string | null) | Media;
          /**
           * Usada apenas enquanto não houver upload — ex.: placeholders do Unsplash.
           */
          externalUrl?: string | null;
          /**
           * Descreve a imagem para leitores de tela. Deixe vazio se for decorativa.
           */
          alt: string;
        };
        tone: 'purple' | 'light' | 'yellow';
        /**
         * Opcional — usado apenas como referência editorial.
         */
        relatedProject?: (string | null) | Project;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * As camadas de mudança e o PDF para download.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theory-of-change".
 */
export interface TheoryOfChange {
  id: string;
  /**
   * A numeração 01, 02… é gerada a partir da ordem desta lista.
   */
  goals?:
    | {
        eyebrow: string;
        title: string;
        body: string;
        image: {
          /**
           * Tem prioridade sobre a URL externa.
           */
          media?: (string | null) | Media;
          /**
           * Usada apenas enquanto não houver upload — ex.: placeholders do Unsplash.
           */
          externalUrl?: string | null;
          /**
           * Descreve a imagem para leitores de tela. Deixe vazio se for decorativa.
           */
          alt: string;
        };
        tone: 'purple' | 'black' | 'light';
        id?: string | null;
      }[]
    | null;
  pdf: {
    label: string;
    /**
     * Quando preenchido, tem prioridade sobre o caminho abaixo.
     */
    file?: (string | null) | Media;
    /**
     * Usado enquanto o arquivo não é enviado.
     */
    href?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Abertura da listagem de publicações.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications-page".
 */
export interface PublicationsPage {
  id: string;
  eyebrow: string;
  title: string;
  description?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Abertura da listagem de projetos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-page".
 */
export interface PortfolioPage {
  id: string;
  eyebrow: string;
  title: string;
  description?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Etapas do atendimento, princípios e as listas de contratação.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: string;
  /**
   * A numeração 01, 02… é gerada a partir da ordem desta lista.
   */
  steps?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Opções do campo "área de atuação" no formulário.
   */
  areas?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Opções do bloco "disponibilidade" no formulário. Tire um dia da lista para deixar de oferecê-lo.
   */
  availabilityDays?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Opções de período no bloco "disponibilidade" do formulário.
   */
  availabilityPeriods?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  heroImage: {
    /**
     * Tem prioridade sobre a URL externa.
     */
    media?: (string | null) | Media;
    /**
     * Usada apenas enquanto não houver upload — ex.: placeholders do Unsplash.
     */
    externalUrl?: string | null;
    /**
     * Descreve a imagem para leitores de tela. Deixe vazio se for decorativa.
     */
    alt: string;
  };
  principles?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  contracted?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  received?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Navegação, contato e números usados em mais de uma página.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  /**
   * Aparece no header e no rodapé, na mesma ordem.
   */
  nav?:
    | {
        label: string;
        /**
         * Rota interna ("/portfolio") ou âncora ("/#entregamos").
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  contact: {
    email: string;
    phone: string;
    address: string;
  };
  /**
   * Exibidos no hero da home e na página de contato.
   */
  metrics?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        body?: T;
      };
  affiliations?:
    | T
    | {
        label?: T;
        id?: T;
      };
  showcase?:
    | T
    | {
        client?: T;
        category?: T;
        title?: T;
        description?: T;
        image?:
          | T
          | {
              media?: T;
              externalUrl?: T;
              alt?: T;
            };
        tone?: T;
        relatedProject?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theory-of-change_select".
 */
export interface TheoryOfChangeSelect<T extends boolean = true> {
  goals?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        body?: T;
        image?:
          | T
          | {
              media?: T;
              externalUrl?: T;
              alt?: T;
            };
        tone?: T;
        id?: T;
      };
  pdf?:
    | T
    | {
        label?: T;
        file?: T;
        href?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications-page_select".
 */
export interface PublicationsPageSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  description?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-page_select".
 */
export interface PortfolioPageSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  description?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  steps?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  areas?:
    | T
    | {
        label?: T;
        id?: T;
      };
  availabilityDays?:
    | T
    | {
        label?: T;
        id?: T;
      };
  availabilityPeriods?:
    | T
    | {
        label?: T;
        id?: T;
      };
  heroImage?:
    | T
    | {
        media?: T;
        externalUrl?: T;
        alt?: T;
      };
  principles?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  contracted?:
    | T
    | {
        label?: T;
        id?: T;
      };
  received?:
    | T
    | {
        label?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  nav?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
      };
  metrics?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}