/**
 * Endereços herdados do WordPress anterior, levantados no acervo do Wayback
 * Machine para o domínio move.social. Duas listas, com destinos diferentes de
 * propósito:
 *
 * - `LEGACY_REDIRECTS` cobre o que foi migrado e tem endereço novo. Um 301
 *   transfere o histórico da URL antiga e leva a pessoa ao conteúdo certo. Os
 *   pares saem do cruzamento entre o acervo e os slugs do CMS; onde o slug mudou
 *   na migração, a correspondência foi conferida uma a uma.
 * - `LEGACY_GONE` cobre o que não veio para o site novo: notícias, vagas,
 *   relatórios anuais e páginas de serviço. Aqui um 301 para a listagem seria
 *   lido como soft 404 — o buscador mantém o endereço na fila e continua
 *   pedindo. O 410 diz que o recurso saiu em definitivo, que é a única resposta
 *   que faz o endereço sair do índice.
 *
 * `LEGACY_GONE_PREFIXES` são as seções inteiras do WordPress sem equivalente:
 * taxonomias, autores, arquivos por data e a versão em inglês.
 */

export const LEGACY_REDIRECTS: Record<string, string> = {
  "/a-emergencia-das-organizacoes-da-sociedade-civil-a-crise-da-covid-e-o-aumento-da-mortalidade": "/publicacoes/a-emergencia-das-organizacoes-da-sociedade-civil-a-crise-da-covid-e-o-aumento-da-mortalidade",
  "/a-escuta-de-bebes-e-criancas-pequenas-em-avaliacoes": "/publicacoes/a-escuta-de-bebes-e-criancas-pequenas-em-avaliacoes",
  "/a-relevancia-da-avaliacao-para-o-investimento-social-privado": "/publicacoes/a-relevancia-da-avaliacao-para-o-investimento-social-privado",
  "/abordagem-qualitativa-do-impacto-de-projetossocioambientais": "/publicacoes/abordagem-qualitativa-do-impacto-de-projetossocioambientais",
  "/aceleradoras-de-impacto-avaliacao-da-efetividade": "/publicacoes/avaliacao-da-efetividade-das-aceleradoras",
  "/avaliacao-da-efetividade-de-aceleradoras-de-impacto": "/publicacoes/avaliacao-da-efetividade-das-aceleradoras",
  "/avaliacao-de-impacto": "/publicacoes/avaliacao-de-impacto",
  "/avaliacao-de-projetos-com-tecnologias-digitais-na-educacao-publica-brasileira": "/publicacoes/avaliacao-de-projetos-com-tecnologias-digitais-na-educacao-publica-brasileira",
  "/avaliacao-do-investimento-social-privado-estrategia-organizacional": "/publicacoes/avaliacao-do-investimento-social-privado-estrategia-organizacional",
  "/avaliacao-e-desenvolvimento-organizacional-fortalecendo-estrategias-e-impactos-sociais": "/publicacoes/avaliacao-e-desenvolvimento-organizacional-fortalecendo-estrategias-e-impactos-sociais",
  "/avaliacao-e-justica-social-reflexoes-sobre-complexidade-participacao-e-dinamicas-de-poder-a-partir-da-participacao-no-15a-conferencia-europeia-de-avaliacao": "/publicacoes/avaliacao-e-justica-social-reflexoes-sobre-complexidade-participacao-e-dinamicas-de-poder-a-partir-da-participacao-no-15a-conferencia-europeia-de-avaliacao",
  "/avaliacao-em-saude-a-importancia-dos-modelos-teoricos-para-projetar-impacto-social": "/publicacoes/avaliacao-em-saude-a-importancia-dos-modelos-teoricos-para-projetar-impacto-social",
  "/avaliacao-na-educacao-integral-elaboracao-de-novos-referenciais-para-politicas-e-programas": "/publicacoes/avaliacao-na-educacao-integral-elaboracao-de-novos-referenciais-para-politicas-e-programas",
  "/avaliacao-para-o-investimento-social-privado-comunicar-e-utilizar-a-avaliacao-de-maneira-efetiva": "/publicacoes/avaliacao-para-o-investimento-social-privado-comunicar-e-utilizar-a-avaliacao-de-maneira-efetiva",
  "/avaliacao-para-o-investimento-social-privado-metodologias": "/publicacoes/avaliacao-para-o-investimento-social-privado-metodologias",
  "/avaliacao-por-e-para-mulherescom-abordagem-culturalmente-responsiva-einterseccional-brasil": "/publicacoes/avaliacao-por-e-para-mulherescom-abordagem-culturalmente-responsiva-einterseccional-brasil",
  "/blog": "/publicacoes",
  "/case": "/portfolio",
  "/case/amaz": "/portfolio/amaz",
  "/case/amaz-2": "/portfolio/amaz-2",
  "/case/ambev": "/portfolio/ambev",
  "/case/anpecom": "/portfolio/anpecom",
  "/case/aromeiazero": "/portfolio/aromeiazero",
  "/case/associacao-nova-escola-2": "/portfolio/associacao-nova-escola-2",
  "/case/axa-articulacao-xingu-araguaia": "/portfolio/axa-articulacao-xingu-araguaia",
  "/case/brasal": "/portfolio/brasal",
  "/case/ca-foundation": "/portfolio/ca-foundation",
  "/case/caixa": "/portfolio/caixa",
  "/case/cedaps-centro-de-promocao-da-saude": "/portfolio/cedaps-centro-de-promocao-da-saude",
  "/case/centro-de-estudos-rio-terra": "/portfolio/centro-de-estudos-rio-terra",
  "/case/creas-jundiai-sp": "/portfolio/creas-jundiai-sp",
  "/case/delivery-associates": "/portfolio/delivery-associates",
  "/case/ecosocial": "/portfolio/ecosocial",
  "/case/falm-fundacao-andre-e-lucia-maggi": "/portfolio/falm-fundacao-andre-e-lucia-maggi",
  "/case/ftv-fundacao-telefonica-vivo": "/portfolio/ftv-fundacao-telefonica-vivo",
  "/case/ftv-fundacao-telefonica-vivo-2": "/portfolio/ftv-fundacao-telefonica-vivo-2",
  "/case/ftv-fundacao-telefonica-vivo-3": "/portfolio/ftv-fundacao-telefonica-vivo-3",
  "/case/fund-for-shared-insight": "/portfolio/fund-for-shared-insight",
  "/case/fundacao-lemann": "/portfolio/fundacao-lemann",
  "/case/fundacao-novartis": "/portfolio/fundacao-novartis",
  "/case/fundacao-renova": "/portfolio/fundacao-renova",
  "/case/fundacao-tide-setubal": "/portfolio/fundacao-tide-setubal",
  "/case/fundo-vale": "/portfolio/fundo-vale",
  "/case/fundo-vale-2": "/portfolio/fundo-vale-2",
  "/case/gife": "/portfolio/gife",
  "/case/gife-2": "/portfolio/gife-2",
  "/case/greenpeace-brasil": "/portfolio/greenpeace-brasil",
  "/case/greenpeace-brasil-2": "/portfolio/greenpeace-brasil-2",
  "/case/hydro": "/portfolio/hydro",
  "/case/ice-instituto-de-cidadania-empresarial": "/portfolio/ice-instituto-de-cidadania-empresarial",
  "/case/ice-instituto-de-cidadania-empresarial-2": "/portfolio/ice-instituto-de-cidadania-empresarial-2",
  "/case/ice-instituto-de-cidadania-empresarial-3": "/portfolio/ice-instituto-de-cidadania-empresarial-3",
  "/case/imaflora-instituto-de-manejo-e-certificacao-florestal-e-agricola": "/portfolio/imaflora-instituto-de-manejo-e-certificacao-florestal-e-agricola",
  "/case/inesc-instituto-de-estudos-socioeconomicos": "/portfolio/inesc-instituto-de-estudos-socioeconomicos",
  "/case/inpacto-e-laudes-foundation": "/portfolio/inpacto-e-laudes-foundation",
  "/case/instituto-acp": "/portfolio/instituto-acp",
  "/case/instituto-afrolatinas": "/portfolio/instituto-afrolatinas",
  "/case/instituto-alana": "/portfolio/instituto-alana",
  "/case/instituto-arapyau": "/portfolio/instituto-arapyau",
  "/case/instituto-bauducco": "/portfolio/instituto-bauducco",
  "/case/instituto-ca": "/portfolio/instituto-ca",
  "/case/instituto-ca-2": "/portfolio/instituto-ca-2",
  "/case/instituto-ca-3": "/portfolio/instituto-ca-3",
  "/case/instituto-de-pesquisas-ecologicas-ipe": "/portfolio/instituto-de-pesquisas-ecologicas-ipe",
  "/case/instituto-helda-gerdau": "/portfolio/instituto-helda-gerdau",
  "/case/instituto-natura": "/portfolio/instituto-natura",
  "/case/instituto-procomum": "/portfolio/instituto-procomum",
  "/case/instituto-procomum-2": "/portfolio/instituto-procomum-2",
  "/case/instituto-reuna": "/portfolio/instituto-reuna",
  "/case/instituto-unibanco": "/portfolio/instituto-unibanco",
  "/case/isa-cteep": "/portfolio/isa-cteep",
  "/case/isa-instituto-socioambiental": "/portfolio/isa-instituto-socioambiental",
  "/case/isa-instituto-socioambiental-2": "/portfolio/isa-instituto-socioambiental-2",
  "/case/itau-social": "/portfolio/itau-social",
  "/case/itau-social-2": "/portfolio/itau-social-2",
  "/case/itv-instituto-tecnologico-vale": "/portfolio/itv-instituto-tecnologico-vale",
  "/case/klabin": "/portfolio/klabin",
  "/case/labora": "/portfolio/labora",
  "/case/laudes-foundation": "/portfolio/laudes-foundation",
  "/case/laudes-foundation-2": "/portfolio/laudes-foundation-2",
  "/case/omidyar": "/portfolio/omidyar",
  "/case/oxfam-brasil": "/portfolio/oxfam-brasil",
  "/case/oxfam-brasil-2": "/portfolio/oxfam-brasil-2",
  "/case/pimp-my-carroca": "/portfolio/pimp-my-carroca",
  "/case/programa-escolas-criativas": "/portfolio/escolas-criativas",
  "/case/programa-mundial-de-alimentos-da-onu": "/portfolio/programa-mundial-de-alimentos-da-onu",
  "/case/projeto-guri": "/portfolio/projeto-guri",
  "/case/quintessa": "/portfolio/quintessa",
  "/case/raiadrogasil": "/portfolio/raiadrogasil",
  "/case/rede-cruzada": "/portfolio/rede-cruzada",
  "/case/rede-marista-de-solidariedade": "/portfolio/rede-marista-de-solidariedade",
  "/case/rumo-logistica": "/portfolio/rumo-logistica",
  "/case/santander": "/portfolio/santander",
  "/case/scbi-sociedade-brasileira-da-cultura-inglesa": "/portfolio/scbi-sociedade-brasileira-da-cultura-inglesa",
  "/case/sesai-secretaria-de-saude-indigena": "/portfolio/sesai-secretaria-de-saude-indigena",
  "/case/sesc": "/portfolio/sesc",
  "/case/sustenidos": "/portfolio/sustenidos",
  "/case/synergos": "/portfolio/synergos",
  "/case/syngenta": "/portfolio/syngenta",
  "/case/umbrasil-uniao-marista-do-brasil": "/portfolio/umbrasil-uniao-marista-do-brasil",
  "/case/umbrasil-uniao-marista-do-brasil-2": "/portfolio/umbrasil-uniao-marista-do-brasil-2",
  "/case/unesco": "/portfolio/unesco",
  "/case/unicef-fundo-das-nacoes-unidas": "/portfolio/unicef-fundo-das-nacoes-unidas",
  "/case/unifesp-universidade-federal-de-sao-paulo": "/portfolio/unifesp-universidade-federal-de-sao-paulo",
  "/case/uwb-united-way-brasil": "/portfolio/uwb-united-way-brasil",
  "/case/uwb-united-way-brasil-2": "/portfolio/uwb-united-way-brasil-2",
  "/case/vox-capital": "/portfolio/vox-capital",
  "/case/yunus-negocios-sociais": "/portfolio/yunus-negocios-sociais",
  "/casos": "/portfolio",
  "/contato-2": "/contato",
  "/diversidade-metodologica-e-incidencia-estrategica": "/publicacoes/diversidade-metodologica-e-incidencia-estrategica",
  "/download": "/publicacoes",
  "/ferramenta-de-autodiagnostico-para-o-desenvolvimento-institucional": "/publicacoes/ferramenta-de-autodiagnostico-para-o-desenvolvimento-institucional",
  "/guia-de-tendencias-e-praticas-do-investimento-social-empresarial": "/publicacoes/guia-de-tendencias-e-praticas-do-investimento-social-empresarial",
  "/guia-de-tendencias-e-praticas-do-investimento-social-familiar": "/publicacoes/guia-de-tendencias-e-praticas-do-investimento-social-familiar",
  "/guia-pratico-avaliacao-para-negocios-de-impacto-social": "/publicacoes/guia-pratico-avaliacao-para-negocios-de-impacto-social",
  "/historias-de-vida-eavaliacoes-de-impacto": "/publicacoes/historias-de-vida-eavaliacoes-de-impacto",
  "/home": "/",
  "/igarite-sistematizacao-do-ensino-presencial-com-mediacao-tecnologica-no-estado-do-amazonas": "/publicacoes/igarite-sistematizacao-do-ensino-presencial-com-mediacao-tecnologica-no-estado-do-amazonas",
  "/matriz-avaliativa-como-dispositivo-estrategico": "/publicacoes/matriz-avaliativa-como-dispositivo-estrategico",
  "/metodos-mistos-para-avaliar-resultados-o-caso-do-programa-excelencia-em-gestao-educacional-da-fundacao-itau-social": "/publicacoes/metodos-mistos-para-avaliar-resultados-o-caso-do-programa-excelencia-em-gestao-educacional-da-fundacao-itau-social",
  "/metricas-em-negocios-de-impacto-social": "/publicacoes/metricas-em-negocios-de-impacto-social",
  "/metricas-para-negocios-de-impacto-social": "/publicacoes/metricas-para-negocios-de-impacto-social",
  "/modelo-c": "/publicacoes/modelo-c",
  "/modelo-c-2-0": "/publicacoes/modelo-c-2-0",
  "/monitorar-programas-sociais-o-caso-do-banco-santander": "/publicacoes/monitorar-programas-sociais-o-caso-do-banco-santander",
  "/monitorar-resultados": "/publicacoes/monitorar-resultados",
  "/noticias-do-campoavaliacao-da-articulacao-xingu-araguaia-axa": "/publicacoes/noticias-do-campoavaliacao-da-articulacao-xingu-araguaia-axa",
  "/o-investimento-social-privado-e-o-desejo-deincidir-nas-politicas-publicas-de-educacao-aprendizagens": "/publicacoes/o-investimento-social-privado-e-o-desejo-deincidir-nas-politicas-publicas-de-educacao-aprendizagens",
  "/o-que-o-investimento-social-privado-pode-fazer-pelas-mudancas-climaticas": "/publicacoes/o-que-o-investimento-social-privado-pode-fazer-por-mudancas-climaticas",
  "/o-que-o-investimento-social-privado-pode-fazer-por": "/publicacoes",
  "/o-que-o-investimento-social-privado-pode-fazer-por-agua": "/publicacoes/o-que-o-investimento-social-privado-pode-fazer-por-agua-2",
  "/o-que-o-investimento-social-privado-pode-fazer-por-agua-2": "/publicacoes/o-que-o-investimento-social-privado-pode-fazer-por-agua-2",
  "/o-que-o-investimento-social-privado-pode-fazer-por-cidades-sustentaveis": "/publicacoes/o-que-o-investimento-social-privado-pode-fazer-por-cidades-sustentaveis",
  "/o-que-o-investimento-social-privado-pode-fazer-por-democracia": "/publicacoes/o-que-o-investimento-social-privado-pode-fazer-por-democracia",
  "/o-que-o-investimento-social-privado-pode-fazer-por-equidade-racial": "/publicacoes/o-que-o-investimento-social-privado-pode-fazer-por-equidade-racial",
  "/o-que-o-investimento-social-privado-pode-fazer-por-gestao-publica": "/publicacoes/o-que-o-investimento-social-privado-pode-fazer-por-gestao-publica",
  "/o-que-o-investimento-social-privado-pode-fazer-por-migracoes-e-refugiados": "/publicacoes/o-que-o-investimento-social-privado-pode-fazer-por-migracoes-e-refugiados",
  "/o-que-o-investimento-social-privado-pode-fazer-por-mudancas-climaticas": "/publicacoes/o-que-o-investimento-social-privado-pode-fazer-por-mudancas-climaticas",
  "/o-que-o-investimento-social-privado-pode-fazer-por-seguranca-publica-e-justica-criminal": "/publicacoes/o-que-o-investimento-social-privado-pode-fazer-por-seguranca-publica-e-justica-criminal",
  "/o-que-o-isp-pode-fazer-pelos-direitos-das-mulheres": "/publicacoes/o-que-o-isp-pode-fazer-por-direito-das-mulheres",
  "/o-que-o-isp-pode-fazer-por-ciencia-e-informacao": "/publicacoes/o-que-o-isp-pode-fazer-por-ciencia-e-informacao",
  "/o-que-o-isp-pode-fazer-por-direito-das-mulheres": "/publicacoes/o-que-o-isp-pode-fazer-por-direito-das-mulheres",
  "/o-que-um-sujeito-oculto-pode-revelar": "/publicacoes/o-que-um-sujeito-oculto-pode-revelar",
  "/o-renascer-de-uma-estrategia-metodos-mistos-em-planejamento": "/publicacoes/o-renascer-de-uma-estrategia-metodos-mistos-em-planejamento",
  "/observacao-participante-potenciais-e-limites": "/publicacoes/observacao-participante-potenciais-e-limites",
  "/para-decolonizar-a-avaliacao-uma-analise-critica-a-partir-da-teoria-da-decolonialidade": "/publicacoes/para-decolonizar-a-avaliacao-uma-analise-critica-a-partir-da-teoria-da-decolonialidade",
  "/para-objetos-complexos-olhares-plurais-a-importancia-dos-metodos-mistos-para-planejar-e-avaliar": "/publicacoes/para-objetos-complexos-olhares-plurais-a-importancia-dos-metodos-mistos-para-planejar-e-avaliar",
  "/politicas-publicas-para-o-ensino-de-ingles-um-panorama-das-experiencias-na-rede-publica-brasileira": "/publicacoes/politicas-publicas-para-o-ensino-de-ingles-um-panorama-das-experiencias-na-rede-publica-brasileira",
  "/projeto": "/portfolio",
  "/rosa-dos-ventos": "/publicacoes/rosa-dos-ventos",
  "/sobre": "/",
  "/tendencias-e-praticas-do-investimento-social-empresarial-gife": "/publicacoes/guia-de-tendencias-e-praticas-do-investimento-social-empresarial",
  "/teoria-de-mudanca": "/teoria-da-mudanca",
  "/teoria-de-mudanca-2": "/teoria-da-mudanca",
  "/teorias-de-mudanca": "/publicacoes/teorias-de-mudanca",
  "/teorias-de-mudancas-integrativas": "/publicacoes/teorias-de-mudancas-integrativas",
};

export const LEGACY_GONE: ReadonlySet<string> = new Set([
  "/2011",
  "/2012",
  "/2013",
  "/2014",
  "/2015",
  "/2016",
  "/2017",
  "/2018",
  "/2019",
  "/2020",
  "/2021",
  "/2022",
  "/2023",
  "/2024",
  "/2025",
  "/2026",
  "/a-expansao-das-fronteiras-um-olhar-sobre-o-viii-seminario-nacional-da-rede-brasileira-de-monitoramento-e-avaliacao",
  "/a-filantropia-isolada",
  "/a-narrativa-da-letalidade-da-populacao-negra-brasileira-baseada-em-fatos-dados-reais",
  "/a-urgencia-de-praticas-antirracistas",
  "/ampliacao-da-rede-de-colaboradores-as",
  "/avaliacao-de-impacto-e-resultados-3",
  "/avaliacao-em-tempos-incertos",
  "/avaliacoes-de-impacto",
  "/caminhos-colaborativos-e-plurais-para-compartilhar-conhecimento-em-avaliacao-de-advocacy-ativismo-e-incidencia-politica",
  "/case/fundacao-lemann-2",
  "/case/itau-social-4",
  "/case/nossas-2",
  "/case/unicef-fundo-das-nacoes-unidas-2",
  "/causalidade-e-avaliacao-nota-tecnica",
  "/celebrar-as-contribuicoes-brasileiras-para-gestao-de-impacto-e-mensuracao",
  "/composicoes-relatorio-anual-da-move-de-2013",
  "/comunicacao-de-causas-reflexoes-e-provocacoes-para-novas-narrativas",
  "/dadospublicos-2015-foi-um-dos-anos-mais-violentos-no-campo-desde-1984",
  "/dadospublicos-acesso-a-escolas-publicas",
  "/dadospublicos-o-avanco-do-desmatamento-da-amazonia-legal",
  "/dadospublicos-o-avanco-do-desmatamento-no-brasil",
  "/dadospublicos-o-desafio-da-permanencia-no-sistema-escolar",
  "/dadospublicos-o-posicionamento-das-mulheres-nas-500-maiores-empresas-do-brasil",
  "/dadospublicos-o-posicionamento-das-mulheres-no-investimento-social-privado",
  "/dadospublicos-raio-x-das-escolas-publicas-brasileiras",
  "/dadospublicos-resultados-do-programa-bracos-abertos",
  "/depoimentos",
  "/diagnostico-politicas-publicas-para-o-ensino-de-ingles",
  "/diversidade-metodologica-relatorio-anual-da-move-de-2015",
  "/equidade-racial-e-o-segundo-tema-da-serie-o-que-o-isp-pode-fazer-por",
  "/estamos-com-uma-vaga-para-estrategista-de-comunicacao-e-marketing",
  "/estudos-e-sistematizacoes-4",
  "/facilitacoes-4",
  "/formacoes-3",
  "/grupos-focais-nota-tecnica",
  "/impacto-coletivo-e-valor-compartilhado-ampliando-a-responsabilidade-integral",
  "/impacto-social-relatorio-anual-da-move-de-2014",
  "/landing",
  "/matriz-avaliativa",
  "/mensagem-a-investidores-sociais-na-pandemia-o-financiamento-flexivel-como-imperativo",
  "/miniguia-pratico-de-monitoramento-programa-itau-social-unicef",
  "/monitoramento-feedback-e-avaliacao-um-novo-tripe-para-aprendizagem-institucional",
  "/monitoramento-gestao-adaptativa",
  "/move-adere-a-carta-conjunta-em-repudio-as-declaracoes-de-bolsonaro-sobre-queimadas-na-amazonia",
  "/move-adere-a-nota-conjunta-em-repudio-a-declaracao-de-bolsonaro-sobre-ativismo-no-brasil",
  "/move-debate-a-importancia-da-mensuracao-do-impacto-social-em-forum-do-sesc-rs",
  "/move-e-parceira-avaliadora-de-evento-e-programa-better-hearts-better-cities-em-sp",
  "/move-no-1-forum-de-financas-sociais-do-nordeste",
  "/move-social-em-defesa-da-democracia",
  "/mudar-para-inovar",
  "/nas-rodas-da-avaliacao-educadora",
  "/newsletter",
  "/nota-tecnica-como-criar-uma-cultura-avaliativa-nas-organizacoes",
  "/o-mito-do-universal-x-o-mito-do-especifico",
  "/o-olhar-atento-ao-genero-raca-e-cultura-nos-processos-avaliativos",
  "/o-problema-da-teoria-de-mudanca-e-a-ausencia-do-problema",
  "/oficina-teoria-de-mudanca-em-avaliacoes-de-impacto-socioambiental",
  "/os-7-desenhos-classicos-da-avaliacao",
  "/perspectivas-sobre-avaliacao-antirracista",
  "/planejamento-estrategico-4",
  "/planejamento-estrategico-gestao-adaptativa",
  "/podcast-metricas-do-impacto-social-com-daniel-brandao",
  "/por-avaliacoes-atentas-aos-contextos-sociais",
  "/por-organizacoes-capazes-de-produzir-impacto-social-positivo",
  "/por-que-considerar-questoes-de-raca-em-processos-de-avaliacao",
  "/praticas-globais-em-gestao-e-mensuracao-de-impacto",
  "/primeiras-historias-relatorio-anual-da-move-de-2012",
  "/processo-de-selecao-estagiario-a-area-gestao-de-projetos",
  "/processo-de-selecao-pesquisador-a-temporaria-o",
  "/qual-a-contribuicao-das-aceleradoras-para-o-impacto-social",
  "/qual-e-o-nosso-jeito-de-promover-impacto-social-positivo",
  "/quarto-seminario-avaliacao-sistematizacao",
  "/se-nao-e-confiando-como",
  "/semana-aprendizagem-move-2018",
  "/sistema-de-monitoramento-e-gestao-de-impacto",
  "/sobre-o-olhar-e-papel-dos-avaliadores",
  "/travessia-relatorio-anual-da-move-de-2016",
  "/uma-analise-do-sinaeb-defesa-da-circulacao-das-ideias",
  "/uma-decada-gerando-conhecimento-e-estrategia-em-impacto-social-positivo",
]);

/**
 * Seções inteiras do WordPress sem equivalente: taxonomias, autores e os arquivos
 * por data. Os anos estão escritos um a um porque o roteador do Next não aplica um
 * parâmetro com regex própria nesta posição — só literais.
 */
export const LEGACY_GONE_PREFIXES = [
  "/tag",
  "/cat",
  "/category",
  "/author",
  "/ecossistema",
  "/servico",
  "/segmento",
  "/en",
  "/projeto",
  "/2011",
  "/2012",
  "/2013",
  "/2014",
  "/2015",
  "/2016",
  "/2017",
  "/2018",
  "/2019",
  "/2020",
  "/2021",
  "/2022",
  "/2023",
  "/2024",
  "/2025",
  "/2026",
] as const;

/**
 * A mesma lista em array, para o `matcher` do proxy: o Next precisa de valores
 * literais no config, e um Set não é enumerável na análise estática do build.
 */
export const LEGACY_GONE_PATHS: readonly string[] = [...LEGACY_GONE];
